spring:
  application:
    name: product-server-service
  config:
    import: optional:configserver:http:/localhost:8888
  data:
    mongodb:
      username: dulan
      password: dulan
      host: localhost
      port: 27017
      database: product
      authentication-database: admin
server:
  port: 8050